- name: "Install"
  hosts: localhost
  vars_files:
    - vars/installs.yml
    - vars/configs.yml
  roles:
    - role: brew
    - role: geerlingguy.mac.mas
      when: mas_installed_apps|length > 0
      tags:
        - mas
    - role: php
      tags: 
        - php
    - role: npm
      tags: 
        - npm

- name: "Configuration"
  hosts: localhost
  vars_files:
    - vars/configs.yml
  roles:
    - role: macos
      tags: 
        - macos
    - role: shell
      tags:
        - shell
