- name: "Install"
  hosts: localhost
  vars_files:
    - vars/installs.yml
    - vars/configs.yml
  roles:
    - role: brew
    - role: geerlingguy.mas
      when: mas_installed_apps|length > 0
      tags:
        - mas
    - role: valet
      tags: 
        - valet

- name: "Configuration"
  hosts: localhost
  roles:
    - role: macos
      tags: 
        - macos
    - role: shell
      tags:
        - shell