- name: Install global composer packages
  composer:
    command: require
    arguments: '{{ item }}'
    global_command: yes
  loop: '{{ composer_packages }}'

- name: Ensure pecl is installed.
  command: 'which pecl'
  register: pecl_installed
  tags:
    - pecl

- name: Fix pecl path
  file:
    src: "/usr/local/lib/php"
    dest: "/usr/local/lib/php/pecl"
    state: link
  tags:
    - pecl_link

- debug: msg="{{ pecl_installed }} is an environment variable"
  tags:
    - pecl

- name: Remove PECL libaries.
  command: "pecl uninstall {{ item }}"
  with_items: "{{ php_pecl_extensions }}"
  tags:
    - pecl

- name: Install PECL libaries.
  shell: "yes '' | pecl install {{ item }}"
  when: pecl_installed is succeeded
  register: pecl_result
  changed_when: pecl_result is succeeded
  failed_when: "not (('already installed' in pecl_result.stdout) or ('install ok:' in pecl_result.stdout))"
  with_items: "{{ php_pecl_extensions }}"
  notify:
    - restart PHP
  tags:
    - pecl

- name: Get PHP Version
  command: "php -r \"$v=explode('.', PHP_VERSION); echo implode('.', array_splice($v, 0, -1));\""
  register: php_version_result
  tags:
    - pecl

- debug:
    msg: "{{ php_version_result.stdout_lines | last }}"
  tags:
    - pecl

- name: Remove PECL libaries from php.ini file
  lineinfile:
    dest: "/usr/local/etc/php/{{ php_version_result.stdout_lines | last }}/php.ini"
    regexp: '\"{{ item }}.so\"$'
    state: absent
  with_items: "{{ php_pecl_extensions }}"
  notify:
    - restart PHP
  tags:
    - pecl
